export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const FETCH_NEWS_LIST = 'FETCH_NEWS_LIST';

export const FETCH_REFRESH_REQUEST = 'FETCH_REFRESH_REQUEST';
export const FETCH_REFRESH_SUCCESS = 'FETCH_REFRESH_SUCCESS';
export const FETCH_REFRESH_FAILURE = 'FETCH_REFRESH_FAILURE';
export const REFRESH_NEWS_LIST = 'REFRESH_NEWS_LIST';
export const SET_LOCAL_ARTICLES = 'SET_LOCAL_ARTICLES';
export const RESET_PAGE_COUNT = 'RESET_PAGE_COUNT';
